@echo off
echo Creating venv...
python -m venv venv
echo Activating venv...
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Initializing DB...
python init_db.py
echo Seeding data...
python seed.py
echo Starting server...
echo Setup complete.
